/** Product copy — heroes, sections, and UI strings. See docs/messaging.md */

export const overviewCopy = {
  hero: {
    eyebrow: "Verifiable risk oracle",
    title: "Prove inference. Publish score. Adjust collateral.",
    body: "Zyocra attests that a quantized LoRA-adapted risk model executed correctly off-chain, verifies the result on EVM, and benchmarks EZKL against a hand-optimized Circom path.",
    ctaPrimary: "Walk pipeline",
    ctaSecondary: "Benchmark comparison",
  },
  flow: {
    label: "Pipeline",
    title: "Epoch → prove → verify → parameter update",
    description:
      "Six operational screens mirror the oracle workload. Demo data uses epoch-2026-041 until prover and contract hooks land.",
  },
  system: {
    label: "Stack",
    title: "Monorepo boundaries",
    description:
      "Each layer owns artifacts with reproducible hashes—no hosted prover or paid RPC required.",
  },
  metrics: {
    label: "Benchmark axes",
    title: "What the comparison measures",
    description:
      "Headline table in Benchmarks. Values populate when Milestone 5 runs complete on one machine spec.",
  },
  entry: {
    label: "Demo",
    title: "Walk the six-step pipeline",
    description:
      "Read-only replay of epoch commitments → inputs → prove → verify → score → collateral impact. Regenerate artifacts with bash scripts/e2e_phase1.sh in the terminal.",
  },
  faq: {
    label: "FAQ",
    title: "Common questions",
    description:
      "Scope, guarantees, and what recruiters should look for in the benchmark artifact.",
  },
};

export const systemLayers = [
  {
    num: "01",
    title: "ml-base",
    body: "Tabular MLP, LoRA adapters (W′ = W + AB), ONNX export, Q8.8 quantization, float reference eval.",
  },
  {
    num: "02",
    title: "circuits-baseline",
    body: "ONNX → EZKL compile → trusted setup → proof → autogenerated Solidity verifier.",
  },
  {
    num: "03",
    title: "circuits-custom",
    body: "Circom gadgets for low-rank delta, dense inference subgraph, optional activation approximation.",
  },
  {
    num: "04",
    title: "contracts",
    body: "RiskOracle commits scores with proof metadata; RiskConsumer maps buckets to collateral policy.",
  },
];

export const headlineMetrics = [
  { label: "Constraint count", value: "—", detail: "R1CS / PLONK constraints, both paths" },
  { label: "Peak RAM", value: "—", detail: "Prover process high-water mark", accent: true },
  { label: "Proof time", value: "—", detail: "Wall clock, single borrower vector" },
  { label: "Verify gas", value: "—", detail: "Foundry snapshot on Anvil", accent: false },
  { label: "Proof size", value: "—", detail: "Serialized proof bytes", accent: true },
  { label: "Quant error", value: "—", detail: "|float32 − fixed-point| on score" },
];

export const bucketThresholds = [
  {
    label: "LOW",
    range: "0.00 – 0.55",
    action: "Standard collateral factor · baseline borrow spread",
  },
  {
    label: "MEDIUM",
    range: "0.55 – 0.80",
    action: "Reduced collateral factor · +45 bps borrow spread",
  },
  {
    label: "HIGH",
    range: "0.80 – 0.92",
    action: "Freeze new borrows · tighten liquidation buffer",
  },
  {
    label: "CRITICAL",
    range: "> 0.92",
    action: "Flag delayed mitigation · no instant liquidation",
  },
];

export const provePaths = {
  ezkl: {
    name: "EZKL baseline",
    description:
      "Full ONNX graph compiled to PLONK. Measures end-to-end compiler cost for quantized LoRA inference.",
  },
  circom: {
    name: "Circom LoRA path",
    description:
      "Hand-written R1CS for W′ = W + AB and selected layers. Tests whether structure beats generic compilation.",
  },
};

export const benchmarkMethodology = [
  "Single machine spec recorded in benchmarks/scripts/env.txt.",
  "Same borrower vector, quantization profile, and public-input policy on both paths.",
  "Gas from Foundry `gas_report` on local Anvil—no mainnet fork.",
  "Proof size and peak RAM read from prover logs, not self-reported.",
];

export const benchmarkArtifacts = [
  "benchmarks/raw-results/ezkl-epoch-2026-041.json",
  "benchmarks/raw-results/circom-epoch-2026-041.json",
  "benchmarks/plots/constraints-diff.svg",
  "benchmarks/plots/verify-gas.svg",
];

export const footerCopy = {
  status: "Local-first · Foundry + EZKL + Circom",
  headline: "Prove inference.\nPublish parameters.",
  lede:
    "Verifiable LoRA risk oracle for DeFi—benchmark-driven zkML with on-chain verification and collateral policy updates.",
  cta: "Walk pipeline",
};
