/** Product copy — heroes, sections, and UI strings. See docs/messaging.md */

export type HeroLayer = {
  id: string;
  index: string;
  title: string;
  bullets: string[];
};

export const overviewCopy = {
  hero: {
    eyebrow: "Verifiable risk oracle",
    title: "Prove inference.\nPublish score.\nAdjust collateral.",
    body: "Zyocra attests that a quantized LoRA-adapted risk model executed correctly off-chain, verifies the result on EVM, and benchmarks EZKL against a hand-optimized Circom path.",
    ctaPrimary: "Walk pipeline",
    ctaSecondary: "Benchmark comparison",
    layers: [
      {
        id: "commit",
        index: "01",
        title: "Commit layer",
        bullets: [
          "Register model and adapter hashes on RiskOracle.",
          "Seal ONNX export and quantization profile per epoch.",
          "Reject proofs generated under undeclared weights.",
        ],
      },
      {
        id: "prove",
        index: "02",
        title: "Prove layer",
        bullets: [
          "Run EZKL on the full risk MLP ONNX graph.",
          "Emit witness, proof bytes, and public input instances.",
          "Compare against Circom head subgraph in benchmarks.",
        ],
      },
      {
        id: "verify",
        index: "03",
        title: "Verify layer",
        bullets: [
          "Check proof via Halo2Verifier on local Anvil or testnet.",
          "Bind scoreBps to publicInputs[6] after verification.",
          "Gate oracle admission before consumer policy runs.",
        ],
      },
      {
        id: "apply",
        index: "04",
        title: "Apply layer",
        bullets: [
          "Map verified score to LOW / MEDIUM / HIGH / CRITICAL bucket.",
          "Update collateral factor and borrow spread on-chain.",
          "Emit audit trail without model-triggered liquidation.",
        ],
      },
    ] satisfies HeroLayer[],
  },
  flow: {
    label: "Pipeline",
    title: "Epoch → prove → verify → parameter update",
    description:
      "Six operational screens mirror the oracle workload. Demo data uses epoch-2026-041 until prover and contract hooks land.",
  },
  system: {
    label: "Stack",
    title: "Monorepo boundaries",
    description:
      "Each layer owns artifacts with reproducible hashes—no hosted prover or paid RPC required.",
  },
  metrics: {
    label: "Benchmark axes",
    title: "What the comparison measures",
    description:
      "Headline table in Benchmarks. Values populate when Milestone 5 runs complete on one machine spec.",
  },
  entry: {
    label: "Demo",
    title: "Walk the six-step pipeline",
    description:
      "Read-only replay of epoch commitments → inputs → prove → verify → score → collateral impact. Regenerate artifacts with bash scripts/e2e_phase1.sh in the terminal.",
  },
  faq: {
    label: "FAQ",
    title: "Common questions",
    description:
      "Scope, guarantees, and what recruiters should look for in the benchmark artifact.",
  },
};

export const systemLayers = [
  {
    num: "01",
    title: "ml-base",
    body: "Tabular MLP, LoRA adapters (W′ = W + AB), ONNX export, Q8.8 quantization, float reference eval.",
  },
  {
    num: "02",
    title: "circuits-baseline",
    body: "ONNX → EZKL compile → trusted setup → proof → autogenerated Solidity verifier.",
  },
  {
    num: "03",
    title: "circuits-custom",
    body: "Circom gadgets for low-rank delta, dense inference subgraph, optional activation approximation.",
  },
  {
    num: "04",
    title: "contracts",
    body: "RiskOracle commits scores with proof metadata; RiskConsumer maps buckets to collateral policy.",
  },
];

export const headlineMetrics = [
  { label: "Constraint count", value: "—", detail: "R1CS / PLONK constraints, both paths" },
  { label: "Peak RAM", value: "—", detail: "Prover process high-water mark", accent: true },
  { label: "Proof time", value: "—", detail: "Wall clock, single borrower vector" },
  { label: "Verify gas", value: "—", detail: "Foundry snapshot on Anvil", accent: false },
  { label: "Proof size", value: "—", detail: "Serialized proof bytes", accent: true },
  { label: "Quant error", value: "—", detail: "|float32 − fixed-point| on score" },
];

export const bucketThresholds = [
  {
    label: "LOW",
    range: "0.00 – 0.55",
    action: "Standard collateral factor · baseline borrow spread",
  },
  {
    label: "MEDIUM",
    range: "0.55 – 0.80",
    action: "Reduced collateral factor · +45 bps borrow spread",
  },
  {
    label: "HIGH",
    range: "0.80 – 0.92",
    action: "Freeze new borrows · tighten liquidation buffer",
  },
  {
    label: "CRITICAL",
    range: "> 0.92",
    action: "Flag delayed mitigation · no instant liquidation",
  },
];

export const provePaths = {
  ezkl: {
    name: "EZKL baseline",
    description:
      "Full ONNX graph compiled to PLONK. Measures end-to-end compiler cost for quantized LoRA inference.",
  },
  circom: {
    name: "Circom LoRA path",
    description:
      "Hand-written R1CS for W′ = W + AB and selected layers. Tests whether structure beats generic compilation.",
  },
};

export const benchmarkMethodology = [
  "Single machine spec recorded in benchmarks/scripts/env.txt.",
  "Same borrower vector, quantization profile, and public-input policy on both paths.",
  "Gas from Foundry `gas_report` on local Anvil—no mainnet fork.",
  "Proof size and peak RAM read from prover logs, not self-reported.",
];

export const benchmarkArtifacts = [
  "benchmarks/raw-results/ezkl-epoch-2026-041.json",
  "benchmarks/raw-results/circom-epoch-2026-041.json",
  "benchmarks/plots/constraints-diff.svg",
  "benchmarks/plots/verify-gas.svg",
];

export const footerCopy = {
  status: "Local-first · Foundry + EZKL + Circom",
  headline: "Prove inference.\nPublish parameters.",
  lede:
    "Verifiable LoRA risk oracle for DeFi—benchmark-driven zkML with on-chain verification and collateral policy updates.",
  cta: "Walk pipeline",
};

export type LegalSection = { title: string; body: string };

export const termsCopy = {
  eyebrow: "Legal",
  title: "Terms of use",
  lede: "Zyocra is an open-source research and portfolio demonstration. By using this site or repository you agree to the terms below.",
  updated: "Last updated · 7 July 2026",
  sections: [
    {
      title: "Demonstration only",
      body: "Zyocra is not a production service, custodian, or financial product. The dashboard replays local artifacts from your own machine. On-chain examples use local Anvil deployments unless you explicitly configure otherwise.",
    },
    {
      title: "No warranty",
      body: "Software, circuits, contracts, and documentation are provided as-is without warranty of any kind. You are responsible for reviewing code, running your own tests, and obtaining professional advice before any mainnet or production use.",
    },
    {
      title: "Not financial advice",
      body: "Risk scores, collateral parameters, and benchmark figures are illustrative outputs from a research stack. They do not constitute investment, lending, or risk-management advice.",
    },
    {
      title: "License",
      body: "Source code is distributed under the repository license. Third-party tools (EZKL, Foundry, Circom, PyTorch, and others) remain subject to their respective licenses.",
    },
    {
      title: "Changes",
      body: "These terms may be updated as the repository evolves. Material changes will be reflected in the changelog.",
    },
  ] satisfies LegalSection[],
};

export const privacyCopy = {
  eyebrow: "Legal",
  title: "Privacy policy",
  lede: "This static demo site is designed to run locally with minimal data collection.",
  updated: "Last updated · 7 July 2026",
  sections: [
    {
      title: "What this site stores",
      body: "The frontend reads JSON files from its public data directory (for example phase1-demo.json) that you generate on your own machine. No account system or cloud backend is required for the default workflow.",
    },
    {
      title: "What this site does not do",
      body: "The default build does not include third-party analytics, advertising trackers, or wallet fingerprinting. Social links open external profiles in a new tab; those sites have their own policies.",
    },
    {
      title: "Local session preferences",
      body: "Your browser may store lightweight preferences (for example pipeline tour state) in sessionStorage. This data never leaves your device.",
    },
    {
      title: "Contact",
      body: "Questions about this policy can be directed via the social links in the site footer.",
    },
  ] satisfies LegalSection[],
};